name 'Bowtie'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'Apache-2.0'
description 'Installs/Configures Bowtie'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
chef_version '>= 14.10'
supports 'ubuntu', '= 18.04'
source_url 'https://github.com/EagleGenomics-cookbooks/Bowtie'
issues_url 'https://github.com/EagleGenomics-cookbooks/Bowtie/issues'
version '1.0.7'
depends 'magic_shell'
depends 'locale'
